---
title: "RMarkdown Class Schedule"
author: "Matthew Beckman"
date: "September 7, 2018"
output: html_notebook
---

# Class Schedule

### SRA 221: Introduction to Security Risk Analytics
This class is a Intro to security risk anayltics, im taking it becuase it is a needed class for my application focus of cyber security.
In this class we will be talking about who is responsible for the security of our information, more infor here [Link](https://ist.psu.edu/students/undergrad/majors/sra)



### STAT 184: Introduction to R Programmaing

This class is a necesary for my data science major, we will be learning about R language and how to use it.
This class is online and it is one of the first online classes iv had, im excited to see all the new things i get to learn, [link](https://bulletins.psu.edu/university-course-descriptions/undergraduate/stat/)


### DS 310: Machine learning for data anayltics

This class teaches the principles of machine leanring and data mining anmd their application in datra science.
DS 310 is needed as one of the main core classes for my data science major and that is why i am taking it. you can find more info here {Link}(https://www.sas.com/en_us/insights/analytics/machine-learning.html)



